<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head>
<!-- Generated by HsColour, http://code.haskell.org/~malcolm/hscolour/ -->
<title>exam-10mar/Problem3/Main.hs</title>
</head>
<body>
<pre><u><font color="#804000">module</font></u> <font color=Green>Problem3</font><font color="#800080">.</font><font color=Green>Main</font> <u><font color="#804000">where</font></u>
<u><font color="#804000">import</font></u> <u><font color="#804000">qualified</font></u> <font color=Green>Problem3</font><font color="#800080">.</font><font color=Green>QuestionCode</font> <u><font color="#804000">as</font></u> <font color=Green>P3Q</font>
main <font color="#808080">=</font> <font color=Green>P3Q</font><font color="#800080">.</font>main

<font color=Blue>-- (Right 0,Right 1738)</font>

<font color=Blue>{-
Motivation:
main runs the same program in the two monads Eval1 and Eval2

From 3(a) (Problem3.Eval_expanded) we know that Eval1 gives either an
error or a new store. Thus, even if the failure is handled, the
modified State will be thrown away. The program will thus return the
emptyStore, which is 0. Eval2, on the other hand, always returns the
new store, even in the case of error. Thus, the state modification
(CMS.put 1738) done before failing propagates through catch and is
visible in the result, which is 1738.

-}</font>
</pre>
</body>
</html>